version: "3.7"

services:
  gatsby-base: &gatsby-base
    build: .

  gatsby:
    <<: *gatsby-base 
    entrypoint: gatsby
    volumes:
      - .:/app
  develop:
    <<: *gatsby-base
    command: gatsby develop -H 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
